const express = require('express')

const router = express.Router()

const adminController = require('../controllers/admin')
const midware = require('../util/middlewares')
const validator = require('../util/validator')

router.get('/dashboard', midware.isAdmin, adminController.getDashboard)
router.get('/profile', midware.isAdmin, adminController.getProfile)
router.get('/candidates', midware.isAdmin, adminController.getCandidates)
router.get('/createTeacher', midware.isAdmin, adminController.getCreateTeacher)
router.get('/createSubject', midware.isAdmin, adminController.getCreateSubject)
router.get('/createAdmin', midware.isAdmin, adminController.getCreateAdmin)
router.get('/assignRole', midware.isAdmin, adminController.getAssignRole)
router.get('/changeTerm', midware.isAdmin, adminController.getChangeTerm)
router.get('/searchStudent', midware.isAdmin, adminController.getSearchStudent)
router.get('/searchTeacher', midware.isAdmin, adminController.getSearchTeacher)
router.get('/postUpload', midware.isAdmin, adminController.getPostUpload)
router.get('/postEdit/:id', midware.isAdmin, adminController.getPostEdit)
router.get('/allPosts', midware.isAdmin, adminController.getAllPosts)
router.get('/deletePost/:id', midware.isAdmin, adminController.deletePost)
    // router.get('/allPosts', midware.isAdmin, adminController.getAllPosts)
    // router.get('/post/:id', midware.isAdmin, adminController.getPost)
router.post('/accept', adminController.postAcceptCandidates)
router.post('/unaccept', adminController.postUnacceptCandidates)
router.post('/createTeacher', adminController.postCreateTeacher)
router.post('/createSubject', adminController.postCreateSubject)
router.post('/createAdmin', adminController.postCreateAdmin)
router.post('/assignRole', adminController.postAssignRole)
router.post('/searchStudent', adminController.postSearchStudent)
router.post('/searchTeacher', adminController.postSearchTeacher)
router.post('/postUpload', midware.isAdmin, validator.postVal, adminController.postPostUpload)
router.post('/postEdit', midware.isAdmin, validator.postVal, adminController.postPostEdit)

module.exports = router